version: '3.8'

x-sourcecBuilder: &sourceBuilder
  context: ./Builders/
  dockerfile: SourceBuilder.Dockerfile

services:
  # #
  # # GLIBC
  # #
  # # Website: https://www.gnu.org/software/libc/started.html
  # # Repo: sourceware.org/git/glibc.git
  # # Docs: https://www.gnu.org/software/libc/documentation.html
  # #
  # glibcStableSourceScratch:
  #   build:
  #     <<: *sourceBuilder
  #     args:
  #       FETCH_CWD: /src
  #       FETCH_PKGS: ack wget
  #       FETCH_CMD: |
  #         mkdir -p /src/glibc
  #         export GLIBC_VERSION=$$(wget -O - -q https://ftp.gnu.org/gnu/glibc/ | ack -o 'glibc-\d{1,2}\.\d{1,2}' | tail -1)
  #         echo "Getting GLIBC Version $${GLIBC_VERSION}"
  #         wget -O - https://ftp.gnu.org/gnu/glibc/$${GLIBC_VERSION}.tar.gz | tar xz -C /src/glibc --strip-components=1
  #       SOURCE_PATH: /src/glibc
  #   image: kristianfoss/source-glibc:stable-scratch

  # #
  # # libisl
  # #
  # # Website: http://freshmeat.sourceforge.net/projects/isl
  # #
  # libislStableSourceScratch:
  #   build:
  #     <<: *sourceBuilder
  #     args:
  #       FETCH_CWD: /src
  #       FETCH_PKGS: ack wget
  #       FETCH_CMD: |
  #         mkdir -p /src/libisl
  #         wget -O - https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.18.tar.bz2 | tar xj -C /src/libisl --strip-components=1
  #       SOURCE_PATH: /src/libisl
  #   image: kristianfoss/source-libisl:stable-scratch

  # #
  # # GCC
  # #
  # # Website: https://gcc.gnu.org/
  # # Repo: gcc.gnu.org/git/gcc.git
  # # Docs: https://gcc.gnu.org/wiki
  # #
  # gccStableSourceScratch:
  #   build:
  #     <<: *sourceBuilder
  #     args:
  #       FETCH_CWD: /src
  #       FETCH_PKGS: ack wget
  #       FETCH_CMD: |
  #         mkdir -p /src/gcc
  #         export GCC_VERSION=$$(wget -O - -q https://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/ | ack -o 'gcc-\d{1,2}\.\d{1,2}\.\d{1,2}' | tail -1)
  #         echo "Getting GCC Version $${GCC_VERSION}"
  #         wget -O - https://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/$${GCC_VERSION}/$${GCC_VERSION}.tar.xz | tar xJ -C /src/gcc --strip-components=1
  #       SOURCE_PATH: /src/gcc
  #   image: kristianfoss/source-gcc:stable-scratch

  # #
  # # Binutils
  # #
  # # Website: https://sourceware.org/binutils/
  # #
  # binutilsStableSourceScratch:
  #   build:
  #     <<: *sourceBuilder
  #     args:
  #       FETCH_CWD: /src
  #       FETCH_PKGS: ack wget
  #       FETCH_CMD: |
  #         mkdir -p /src/binutils
  #         export BINUTILS_VERSION=$$(wget -O - -q https://ftp.gnu.org/gnu/binutils/ | ack -o 'binutils-\d{1,2}\.\d{1,2}\.\d{1,2}' | tail -1)
  #         echo "Getting BIN Utils Version $${BINUTILS_VERSION}"
  #         wget -O - https://ftp.gnu.org/gnu/binutils/$${BINUTILS_VERSION}.tar.xz | tar xJ -C /src/binutils --strip-components=1
  #       SOURCE_PATH: /src/binutils
  #   image: kristianfoss/source-binutils:stable-scratch

  # #
  # # Linux Headers
  # #
  # # Website:
  # #
  # linuxheadersStableSourceScratch:
  #   build:
  #     <<: *sourceBuilder
  #     args:
  #       FETCH_CWD: /src
  #       FETCH_PKGS: ack wget
  #       FETCH_CMD: |
  #         mkdir -p /src/linux-headers
  #         export LINUX_HEADERS_VERSION=$$(wget -O - -q https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ | ack -o 'linux-\d{1,2}\.\d{1,2}\.\d{1,2}' | tail -1)
  #         echo "Getting Linux Headers Version $${LINUX_HEADERS_VERSION}"
  #         wget -O - https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/$${LINUX_HEADERS_VERSION}.tar.xz | tar xJ -C /src/linux-headers --strip-components=1
  #       SOURCE_PATH: /src/linux-headers
  #   image: kristianfoss/source-linux-headers:stable-scratch

  #
  # Go Language
  #
  # Website: https://golang.org/
  # Repo: https://github.com/golang/go
  # Docs: https://golang.org/doc/
  #
  goStableSourceScratch:
    build:
      <<: *sourceBuilder
      args:
        FETCH_CWD: /src
        FETCH_PKGS: wget ack
        FETCH_CMD: |
          export TAG=$$(wget -q -O - https://go.googlesource.com/go/+refs | ack -o 'go\d{1}\.\d{1,2}\.\d{1,2}' | sort -V | tail -1)
          echo "Cloning tag $${TAG}"
          git clone --depth 1 -b $${TAG} https://go.googlesource.com/go
        SOURCE_PATH: /src/go
    image: kristianfoss/source-go:stable-scratch

  #
  # Caddy Source
  #
  # Website: https://caddyserver.com/
  # GitHub: https://github.com/google/cadvisor
  #
  caddyMainSourceScratch:
    build:
      <<: *sourceBuilder
      args:
        FETCH_CWD: /go/src/github.com/caddyserver
        FETCH_CMD: git clone --depth 1 -b master https://github.com/caddyserver/caddy
        SOURCE_PATH: /go/src/github.com/caddyserver/caddy
    image: kristianfoss/source-caddy:main-scratch

  #
  # Minio
  #
  # Website: https://min.io
  # Repo: https://github.com/minio/minio
  # Docs: https://docs.min.io/
  #
  minioStableSourceScratch:
    build:
      <<: *sourceBuilder
      args:
        FETCH_CWD: /usr/lib/go/src/github.com/minio
        FETCH_PKGS: jq wget
        FETCH_CMD: |
          export TAG=$$(wget -O - https://api.github.com/repos/minio/minio/releases/latest | jq -r '.tag_name')
          git clone --depth 1 -b $${TAG} https://github.com/minio/minio.git
        SOURCE_PATH: /usr/lib/go/src/github.com/minio/minio
    image: kristianfoss/source-minio:stable-scratch

  minioMainSourceScratch:
    build:
      <<: *sourceBuilder
      args:
        FETCH_CWD: /usr/lib/go/src/github.com/minio
        FETCH_CMD: |
          git clone --depth 1 -b master https://github.com/minio/minio.git
        SOURCE_PATH: /usr/lib/go/src/github.com/minio/minio
    image: kristianfoss/source-minio:main-scratch

  #
  # Minio MC
  #
  minioMCStableSourceScratch:
    build:
      <<: *sourceBuilder
      args:
        FETCH_CWD: /usr/lib/go/src/github.com/minio
        FETCH_PKGS: jq wget
        FETCH_CMD: |
          export TAG=$$(wget -O - https://api.github.com/repos/minio/mc/releases/latest | jq -r '.tag_name')
          git clone --depth 1 -b $${TAG} https://github.com/minio/mc.git
        SOURCE_PATH: /usr/lib/go/src/github.com/minio/mc
    image: kristianfoss/source-minio-mc:stable-scratch